### ISSUE TITLE
awk: cmd. line:1: fatal: division by zero attempted

### ISSUE THREAD

**Issue by elcortegano** [SAMtoBAM/MUMandCo#14]
I am getting this `awk` error at the beginning of the run. Not sure what causes it and what are its consequences, since the script continues running afterwards.

```
Matching chromosomes based on names, using '_' seperator and filtering chrMT

awk: cmd. line:1: fatal: division by zero attempted
awk: cmd. line:1: fatal: division by zero attempted
awk: cmd. line:1: fatal: division by zero attempted
(standard_in) 2: syntax error

Finding alignment gaps
...
```

I send attached the input for reproducibility ([input.zip](https://github.com/SAMtoBAM/MUMandCo/files/6208366/input.zip)). MUMandCo is run as:

    bash mumandco_v2.4.2.sh -r reference.fa -q query.fa -g 110000000 -o "test"

The script is run with `blast_step=yes`, although this does not seem to alter the output.

**Comment by elcortegano** [comment]
Just created a pull request that I think fixes the issue. It seems that the variable NR is sometimes empty, which leads to an invalid division in the END block of `awk`.

**Comment by SAMtoBAM** [comment]
Hi there, 

You are absolutely right, those would fix these errors

The bigger problem however is the reason they are appearing
It is because MUMmer doesn't find any alignments ...Hence why the NR variable is empty and why the resulting files with the blast option are not generated

From the files you gave me the query and reference section look like they were extracted from a larger fragment, can you try aligning the entire assembly and/or chromosome and then looking for your SVs in any particular location of interest? Plus see if this removes the errors

Thanks!

**Comment by elcortegano** [comment]
Yes, the sample used represents a putative syntenic block, result from mapping an assembly against the reference using mashmap, hence the reduced size (and the possibility that alternative tools fail to align I guess?).

If the whole genome is used, no errors are reported. If the above error is due to MUMmer not finding alignments it makes sense that no variants are found, but wonder if perhaps this could be indicated in the output. As it is now the awk error is very confusing.

Thanks!

**Comment by SAMtoBAM** [comment]
Brilliant, glad to hear that changing the nucmer input solved the problems

I agree, I actually need to create error messages to help anyone diagnose the issues.
Currently there are none and this might be the simpliest one to implement, where there are problems with alignment.
I will try have a look at this soon

Thanks
