### ISSUE TITLE
Analyzing short read assemblies

### ISSUE THREAD

**Issue by koushik1989** [SAMtoBAM/MUMandCo#2]
Dear developers, I intend to use MUM&CO for calling variants between a reference and a newly sequenced strain of _Drosophila_. I have the contigs and also a scaffolded assembly for the same. Looking at your yeast test data I observe the reference and query sequences carry same identifiers. Is this an input mandate to run this tool ? How can I proceed with my short read assembly? I also have a pseudo-chromosomes built using RaGOO, can I use this as query. I also see a warning in the Git page not to use this strategy for short read assembly. Is it due to N's? If I want to use longer accurate contigs for calling variants, then what is the best way to rename the contigs. 
Hoping for a positive response. Thank you

**Comment by SAMtoBAM** [comment]
Apologies, 
I had no notification that there was an issue opened!

I have tested it with illumina data also and it appears to work fine
In fact I avoid all scaffolding like with RaGOO as this only add issues with the gaps introduced (filled with N's)
For me the best is to break all the scaffolds before alignment

In terms of the contig renaming, there is no need for contigs to have any particular naming system
The naming in the test samples is just due to how they were produced

Have you been able to get it working?

**Comment by SAMtoBAM** [comment]
@koushik1989 
is this still an issue?
