### ISSUE TITLE
What does it mean 'imprecise' calls for the VCF

### ISSUE THREAD

**Issue by elcortegano** [SAMtoBAM/MUMandCo#21]
In the README, it is warned that the output VCF contains 'imprecise' calls. What does it mean specifically? does it refer to SM type, length, coordinates, read support, ...?

**Comment by SAMtoBAM** [comment]
Good point, I am not sure if it is the generic use of the term.

For me, I use this in terms of the flanking base for any particular call not being specified in the ref and alt column.
E.g. for an INDEL you might see a ref of ATA and the alt of A. So the common A site remains the anchor for the deletion.
In the VCF I just place the region considered deleted without anchoring it to the upstream base. e.g. ref: AAAAA, alt:<DEL>
In many cases identifying the exact base where the event occurs is complicated due to repetitive regions and alignments at the edge of events.  So that is why I leave it as imprecise in this way.
Hope that is is some way helpful.

**Comment by elcortegano** [comment]
It is helpful, thanks!
