### ISSUE TITLE
MUMandCO v3.8, aborted using example files

### ISSUE THREAD

**Issue by biofcallejas** [SAMtoBAM/MUMandCo#22]
Hi,
I'm using mumandco v3.8, I ran the example and got this message:

cat: DEL100_test.insertion_blast: No such file or directory

It aborted after 3 minutes running, threads=4.
Any suggestion? Many thanks in advance!

**Comment by SAMtoBAM** [comment]
Hi there; 

Real simple issue I forgot to solve sorry!
Just crashed without finding a file because, in the absence of any insertions, the file was never created
I missed it before as it only occurs with the blast option running

Just added a fix if you want to grab the latest mumandco script

Thanks for bringing it to my attention
