### ISSUE TITLE
Aligning different size genomes

### ISSUE THREAD

**Issue by BeetleMilk** [SAMtoBAM/MUMandCo#24]
I want to compare genomes of two ecotypes which are slightly different in size. What should I use with the -g option?

**Comment by SAMtoBAM** [comment]
Hi @BeetleMilk 
The -g option is more so for an estimation of whether the genomes could be considered small, medium or large
It just adjusts the alignment parameters primarily in order to speed up alignment when dealing with larger and larger genomes.
There is below 100Mb, between 100-500Mb and above 500Mb.
So you don't need to worry if the genome size of the two of them are slightly different, just put one and it'll be fine.
Thanks
