### ISSUE TITLE
Detection of ~5kb insertions/deletions

### ISSUE THREAD

**Issue by MFSeidl** [SAMtoBAM/MUMandCo#4]
Hey, 
thank you very much for your tool. I am currently looking into two genomes that have a three of smaller deletions/insertions on one of the chromosomes. The deletions are caused by transposon insertions. When I use a combination of nucmer and bedtools, I am recovering four locations present in one of the strains that correspond to five transposons responsible. When I run your bash script, I am able to recover three out of the five while two transposons are missing. I wonder if you could help me understand what is happening when parsing the nucmer files.
Thanks
MFS

**Comment by SAMtoBAM** [comment]
Howdy, 

I see, it's curious that they are absent, especially since they are so large (~5kb)

If you could send me your data I'd be happy to have a look

**Comment by MFSeidl** [comment]
Hey,

thanks for your reply. The comparison concerns two publicly available yeast genomes (see attached). The deletions are:

chrIII	82738	87989	ID=TY1:chrIII:82402-88325:+;Name=TY1:chrIII:82402-88325:+
chrIII	153908	159820	ID=TY1:chrIII:153905-159820:+;Name=TY1:chrIII:153905-159820:+
chrIII	159488	165408	ID=TY1:chrIII:159489-165408:+;Name=TY1:chrIII:159489-165408:+
chrIII	182673	187943	ID=TY1:chrIII:182349-188256:-;Name=TY1:chrIII:182349-188256:-
chrIII	188864	194115	ID=TY1:chrIII:188530-194452:+;Name=TY1:chrIII:188530-194452:+

The ones identified by MUMandCo are:

chrIII	chrIII	82738	87989	5251	deletion_mobile	82700	83036	
chrIII	chrIII	182673	187943	5270	deletion_mobile	168620	168934	
chrIII	chrIII	188864	194115	5251	deletion_mobile	169207	169544	

The fasta files are attached.

Thanks!

MFS
[Archive.zip](https://github.com/SAMtoBAM/MUMandCo/files/5119929/Archive.zip)

**Comment by SAMtoBAM** [comment]
Ah yes I have found the issue
It comes due to the two missing events being very close to one another (even overlapping in the output you gave me)
chrIII 153908 159820 ID=TY1:chrIII:153905-159820:+;Name=TY1:chrIII:153905-159820:+
chrIII 159488 165408 ID=TY1:chrIII:159489-165408:+;Name=TY1:chrIII:159489-165408:+

When identifying alignment gaps, there are some spurious insertions and deletions where insertions and deletions of the similar size are called at the EXACT same positions
In your case it is because it has detected a smaller insertion within the same region as these two deletions which have been grouped into a single event (considering the overlap)
I have made a little fix to be more lenient in this case, by only removing these spurious insertion/deletion calls if the size of the events are within 5kb of one another. This leaves them in place to be labelled as complicated due to the two events existing within one another

Can you re-download the script (having been modified), re-run and see if that fixes your problem?

**Comment by MFSeidl** [comment]
Hey, 
thanks a lot. I downloaded the script and I now find back this two events:

> chrIII	chrIII	153908	165408	3052	insertion_mobile	148618	151670	complicated
> chrIII	chrIII	153908	165408	11500	deletion_mobile	148618	151670	complicated

It seems the second deletion encompasses both elements, and there is an insertion reported as part of the element. So this seems to match then I assume. thanks a lot for the modification and explanation 

Cheers
Michael

**Comment by SAMtoBAM** [comment]
Perfect, I had the same results

As you can see these two events have apparently occurred within the exact same coordinates 153908-165408 which was the cause for them both being filtered previously. However since their sizes are so different (>5kb) they are now kept.

Hope this has helped
Samuel
