### ISSUE TITLE
What does the label 'complicated' mean?

### ISSUE THREAD

**Issue by Leona123151** [SAMtoBAM/MUMandCo#8]
Hello,
I have been using MUMandCo to detect SVs, but I found that some lines in the result file were followd by 'complicated' label.
These variants are usually labeled insertions or deletions in the SVs type column (In two consecutive rows), so I don't know the exact type.
I tried to read annotations in the source code, but I didn't understand it.
Could you please explain the meaning for me?
![complicated_label_example](https://user-images.githubusercontent.com/37650315/94340513-027dd600-0035-11eb-9298-ef58e7e00ed0.png)

**Comment by SAMtoBAM** [comment]
Hi @Leona123151 

It has been on my mind to properly explain this tag!
As you can see with your output these two events have the same coordinates, however it appears that there is a deletions and an insertion detected in this region. So essentially complicated is just a warning that this may be a complex event

In this case they are kept because the size of the events are very different, therefore making it less likely to be an anomaly of alignment. However when the sizes are also the same they are used to potentially verify inversions (as in some MUMmer processing scripts inversions can be essentially ignored, which makes it look like a gap in both the query and the reference, i.e. looking like a deletion and insertion but they are of the same size, so I use this to verify potential inverted alignments as inversions) and then removed.

Does this help at all?

Thanks

**Comment by Leona123151** [comment]
I think I've got it through your explanation. Thank you very much!
